#!/usr/bin/env python3
"""Score every product under each further view (Stage E) and write the view tables.

Usage: python3 -I tools/build_views.py <repo_root>
Reads   <PKG>/05_Data/products.json (criterion scores from Stage B, unchanged)
        work/stageE/views/views.json (one weight profile per view; FS = the master view)
Writes  <PKG>/05_Data/views.xlsx and views.json
        work/stageE/views/<VIEW>_scores.md   (per-layer ranking for the view writers and the reader)
A view re-weights the same eight criteria; it never changes a fact or a criterion score. The "fit" is
indicative: view score >= 3.6 with no criterion at 1 and not Experimental / Not recommended in the master tiers.
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from edition import E, PKG
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

root = sys.argv[1]; os.chdir(root)
cfg = json.load(open("work/stageE/views/views.json", encoding="utf-8"))
CRIT = cfg["criteria"]; TH = cfg["fit_rules"]["core_threshold"]
ORDER = ["L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8"]
prods = [p for p in json.load(open(PKG + "/05_Data/products.json", encoding="utf-8")) if (p.get("scores") or {}).get("criteria")]

def name(p):
    n = p.get("current_name")
    return (n.get("v") if isinstance(n, dict) else n) or p["id"]

def layer(p):
    l = p.get("layer") or ""
    return l if l in ORDER else (l.split("/")[0] if l.split("/")[0] in ORDER else l)

def score(p, w):
    c = p["scores"]["criteria"]
    return round(sum(c[k] * w[k] for k in CRIT) / sum(w.values()), 2)

for v in cfg["views"]:
    assert sum(v["weights"].values()) == 100, v["id"]
FSW = next(v for v in cfg["views"] if v["id"] == "FS")["weights"]
rows = []
for p in prods:
    tier = (p.get("classification") or {}).get("tier") or ""
    flags = (p.get("classification") or {}).get("flags") or []
    c = p["scores"]["criteria"]
    r = {"id": p["id"], "name": name(p), "layer": layer(p), "tier": tier, "flags": flags, "criteria": c, "scores": {}, "fit": {}}
    for v in cfg["views"]:
        s = score(p, v["weights"]); r["scores"][v["id"]] = s
        blocked = tier.startswith("Experimental") or "Not recommended" in flags
        r["fit"][v["id"]] = "Core candidate" if (s >= TH and min(c.values()) > 1 and not blocked) else "Situational"
    rows.append(r)

# rank within layer, per view
for v in cfg["views"]:
    for L in set(r["layer"] for r in rows):
        group = sorted([r for r in rows if r["layer"] == L], key=lambda r: (-r["scores"][v["id"]], r["name"]))
        for i, r in enumerate(group, 1):
            r.setdefault("rank", {})[v["id"]] = i
lkey = lambda r: (ORDER.index(r["layer"]) if r["layer"] in ORDER else 99, r["layer"])

# ---- views.json
json.dump({"generated_by": "tools/build_views.py", "views": cfg["views"], "fit_rules": cfg["fit_rules"], "products": rows},
          open(PKG + "/05_Data/views.json", "w", encoding="utf-8"), indent=1, ensure_ascii=False)

# ---- markdown per view (for writers and readers)
for v in cfg["views"]:
    if v["id"] == "FS":
        continue
    vid = v["id"]
    out = ["# %s view: scores by layer\n" % v["name"],
           "Generated by `tools/build_views.py` from the Stage B criterion scores. Weights: " +
           ", ".join("%s %d%%" % (k.replace("_", " "), v["weights"][k]) for k in CRIT) + ". " + cfg["fit_rules"]["rule"] + "\n",
           "| Layer | Product | Master tier | FS score | %s score | Rank in layer (FS → %s) | Fit for %s | Lowest criteria |" % (vid, vid, v["short"]),
           "|---|---|---|---:|---:|---|---|---|"]
    for r in sorted(rows, key=lambda r: (lkey(r), r["rank"][vid])):
        low = sorted(r["criteria"].items(), key=lambda kv: kv[1])[:2]
        out.append("| %s | %s | %s | %.2f | %.2f | %d → %d | %s | %s |" % (
            r["layer"], r["name"], r["tier"], r["scores"]["FS"], r["scores"][vid], r["rank"]["FS"], r["rank"][vid], r["fit"][vid],
            ", ".join("%s %d" % (k.replace("_", " "), s) for k, s in low)))
    movers = sorted(rows, key=lambda r: -(abs(r["scores"][vid] - r["scores"]["FS"])))[:15]
    out += ["", "## Largest score changes against the FS view", "", "| Product | Layer | FS | %s | Change | Main drivers: criterion score (weight in this view vs FS) |" % vid, "|---|---|---:|---:|---:|---|"]
    for r in movers:
        d = r["scores"][vid] - r["scores"]["FS"]
        drivers = sorted(CRIT, key=lambda k: -abs((v["weights"][k] - FSW[k]) * (r["criteria"][k] - 3)))[:2]
        out.append("| %s | %s | %.2f | %.2f | %+.2f | %s |" % (r["name"], r["layer"], r["scores"]["FS"], r["scores"][vid], d,
                   "; ".join("%s %d (weight %d%% vs %d%%)" % (k.replace("_", " "), r["criteria"][k], v["weights"][k], FSW[k]) for k in drivers)))
    cnt = {f: sum(1 for r in rows if r["fit"][vid] == f) for f in ("Core candidate", "Situational")}
    cntfs = sum(1 for r in rows if r["fit"]["FS"] == "Core candidate")
    out += ["", "Core candidates: %d under %s, against %d under the FS weights (of %d scored products)." % (cnt["Core candidate"], v["short"], cntfs, len(rows))]
    open("work/stageE/views/%s_scores.md" % vid, "w", encoding="utf-8").write("\n".join(out) + "\n")

# ---- xlsx
wb = Workbook(); ws = wb.active; ws.title = "summary"
ws.append(["View", "Profile", "Weights (%)", "Core candidates", "Situational"])
for v in cfg["views"]:
    ws.append([v["name"], v["profile"], ", ".join("%s %d" % (k, v["weights"][k]) for k in CRIT),
               sum(1 for r in rows if r["fit"][v["id"]] == "Core candidate"), sum(1 for r in rows if r["fit"][v["id"]] == "Situational")])
ws2 = wb.create_sheet("scores")
head = ["Layer", "Product id", "Product", "Master tier"] + CRIT + ["%s score" % v["id"] for v in cfg["views"]] + \
       ["%s fit" % v["id"] for v in cfg["views"]] + ["%s rank in layer" % v["id"] for v in cfg["views"]]
ws2.append(head)
for r in sorted(rows, key=lambda r: (lkey(r), -r["scores"]["FS"])):
    ws2.append([r["layer"], r["id"], r["name"], r["tier"]] + [r["criteria"][k] for k in CRIT] + [r["scores"][v["id"]] for v in cfg["views"]] +
               [r["fit"][v["id"]] for v in cfg["views"]] + [r["rank"][v["id"]] for v in cfg["views"]])
for sh in (ws, ws2):
    for c in sh[1]:
        c.font = Font(bold=True, color="FFFFFF"); c.fill = PatternFill("solid", fgColor="0B1B33"); c.alignment = Alignment(wrap_text=True, vertical="top")
    for i in range(1, sh.max_column + 1):
        sh.column_dimensions[get_column_letter(i)].width = 14
    sh.freeze_panes = "A2"
ws.column_dimensions["B"].width = 80; ws2.column_dimensions["C"].width = 28
wb.save(PKG + "/05_Data/views.xlsx")
print(json.dumps({v["id"]: sum(1 for r in rows if r["fit"][v["id"]] == "Core candidate") for v in cfg["views"]} | {"scored": len(rows)}))
